import jsPDF from 'jspdf';
import { ValuationResult, ValuationInputs, formatCurrency } from './valuation';
import { generateAIAnalysis } from './ai-assistant';

// --- STYLING HELPERS (Shared between Free and Pro) ---

const PAGE_WIDTH = 210; // jsPDF default width in mm
const PAGE_HEIGHT = 297; // jsPDF default height in mm
const MARGIN = 20;
const CONTENT_WIDTH = PAGE_WIDTH - (MARGIN * 2);

const drawHeader = (doc: jsPDF, pageTitle: string, isPro: boolean = false) => {
    doc.setFillColor(15, 23, 42); // slate-900
    doc.rect(0, 0, PAGE_WIDTH, 25, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(isPro ? 'PRO VALUATION REPORT' : 'FREE VALUATION REPORT', MARGIN, 15);
    doc.setFont('helvetica', 'normal');
    doc.text(pageTitle.toUpperCase(), PAGE_WIDTH - MARGIN, 15, { align: 'right' });
    doc.setDrawColor(30, 41, 59); // slate-800
    doc.setLineWidth(0.1);
    doc.line(0, 25, PAGE_WIDTH, 25);
};

const drawFooter = (doc: jsPDF, pageNum: number, totalPages: number) => {
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text(`Generated by SaaS Valuation Wizard • ${new Date().toLocaleDateString()}`, MARGIN, PAGE_HEIGHT - 10);
    doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 10, { align: 'right' });
};

const drawSectionTitle = (doc: jsPDF, title: string, y: number) => {
    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42); // slate-900
    doc.setFont('helvetica', 'bold');
    doc.text(title, MARGIN, y);
    doc.setDrawColor(14, 165, 233); // brand-500
    doc.setLineWidth(1);
    doc.line(MARGIN, y + 2, MARGIN + 20, y + 2);
    return y + 15;
};

const formatPercent = (value?: number, fallback: string = 'N/A') => {
    if (value === undefined || Number.isNaN(value)) return fallback;
    return `${value.toFixed(1)}%`;
};

const formatRatio = (value?: number, fallback: string = 'N/A') => {
    if (value === undefined || Number.isNaN(value)) return fallback;
    return `${value.toFixed(2)}x`;
};

const formatNumber = (value?: number, fallback: string = 'N/A') => {
    if (value === undefined || Number.isNaN(value)) return fallback;
    return `${Math.round(value).toLocaleString()}`;
};

const getBenchmarkStatus = (value?: number, min?: number, max?: number) => {
    if (value === undefined || Number.isNaN(value)) return 'Not provided';
    if (min !== undefined && value < min) return 'Below benchmark';
    if (max !== undefined && value > max) return 'Above benchmark';
    return 'On benchmark';
};

const drawDataTable = (doc: jsPDF, headers: string[], rows: any[][], y: number) => {
    const colWidth = CONTENT_WIDTH / headers.length;

    // Header
    doc.setFillColor(248, 250, 252); // slate-50
    doc.rect(MARGIN, y, CONTENT_WIDTH, 10, 'F');
    doc.setTextColor(71, 85, 105); // slate-600
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    headers.forEach((h, i) => {
        doc.text(h, MARGIN + (i * colWidth) + 5, y + 6.5);
    });

    // Rows
    let currentY = y + 10;
    doc.setFont('helvetica', 'normal');
    rows.forEach((row, i) => {
        if (i % 2 === 0) {
            doc.setFillColor(255, 255, 255);
        } else {
            doc.setFillColor(248, 250, 252);
        }
        doc.rect(MARGIN, currentY, CONTENT_WIDTH, 10, 'F');
        doc.setTextColor(15, 23, 42);
        row.forEach((cell, cellIdx) => {
            doc.text(String(cell), MARGIN + (cellIdx * colWidth) + 5, currentY + 6.5);
        });
        currentY += 10;
    });
    return currentY;
};

const drawSummaryBox = (doc: jsPDF, y: number, companyName: string, avgValuation: number, rangeLow: number, rangeHigh: number, confidence: number) => {
    doc.setFillColor(240, 249, 255);
    doc.setDrawColor(186, 230, 253);
    doc.rect(MARGIN, y, CONTENT_WIDTH, 60, 'FD');

    doc.setFontSize(12);
    doc.setTextColor(51, 65, 85);
    doc.text('Estimated Market Value', MARGIN + 10, y + 15);

    doc.setFontSize(36);
    doc.setTextColor(14, 165, 233);
    doc.setFont('helvetica', 'bold');
    doc.text(formatCurrency(avgValuation), MARGIN + 10, y + 35);

    doc.setFontSize(12);
    doc.setTextColor(71, 85, 105);
    doc.setFont('helvetica', 'normal');
    doc.text(`Valuation Range: ${formatCurrency(rangeLow)} - ${formatCurrency(rangeHigh)}`, MARGIN + 10, y + 48);

    // Confidence Score Circle
    const circleX = PAGE_WIDTH - MARGIN - 30;
    const circleY = y + 30;
    doc.setDrawColor(14, 165, 233);
    doc.setLineWidth(2);
    doc.circle(circleX, circleY, 20);
    doc.setFontSize(14);
    doc.setTextColor(15, 23, 42);
    doc.text(`${confidence}%`, circleX, circleY + 5, { align: 'center' });
    doc.setFontSize(8);
    doc.text('CONFIDENCE', circleX, circleY - 5, { align: 'center' });

    return y + 75;
};

const buildInsights = (data: ValuationResult, inputs: ValuationInputs) => {
    const netProfitMargin = inputs.arr > 0 ? (inputs.netProfit / inputs.arr) * 100 : undefined;
    const ltvCac = inputs.ltv && inputs.cac && inputs.cac > 0 ? inputs.ltv / inputs.cac : undefined;
    const payback = inputs.cac && inputs.mrr && inputs.mrr > 0 ? inputs.cac / inputs.mrr : undefined;
    const revenueMultiple = inputs.arr > 0 ? data.avgValuation / inputs.arr : undefined;

    const qualityFlags: string[] = [];
    if (!inputs.arr) qualityFlags.push('ARR is missing or zero.');
    if (!inputs.netProfit) qualityFlags.push('Net profit is missing or zero.');
    if (inputs.customerChurn === undefined) qualityFlags.push('Customer churn not provided.');
    if (inputs.retentionRate === undefined) qualityFlags.push('Retention rate not provided.');
    if (!inputs.ltv || !inputs.cac) qualityFlags.push('LTV/CAC not provided.');
    if (inputs.grossMargin === undefined) qualityFlags.push('Gross margin not provided.');

    const opportunities: string[] = [];
    if (inputs.customerChurn > 5) opportunities.push('Prioritize churn reduction: highest leverage on valuation.');
    if ((inputs.retentionRate || 0) < 90) opportunities.push('Improve net retention to unlock premium multiples.');
    if ((inputs.grossMargin || 0) < 70) opportunities.push('Lift gross margin (pricing, COGS, infrastructure).');
    if (ltvCac !== undefined && ltvCac < 3) opportunities.push('Improve LTV/CAC above 3x for scalable growth.');
    if ((inputs.growthYoy || 0) < 20) opportunities.push('Increase growth rate to move into higher multiple bands.');
    if (!opportunities.length) opportunities.push('Maintain current trajectory and document moat defensibility.');

    const risks: string[] = [];
    if (inputs.legalIssues && inputs.legalIssues !== 'none') risks.push('Legal issues increase diligence risk.');
    if (inputs.ipOwnership !== 'fully-owned') risks.push('IP ownership risk may reduce buyer confidence.');
    if ((inputs.runway || 0) < 6 && inputs.runway !== undefined) risks.push('Low runway indicates funding risk.');
    if ((inputs.debtLevel || 0) > 0.5) risks.push('High leverage can compress valuation.');
    if (!risks.length) risks.push('No major structural risks flagged from provided inputs.');

    return {
        netProfitMargin,
        ltvCac,
        payback,
        revenueMultiple,
        qualityFlags,
        opportunities,
        risks
    };
};

const DATA_ROOM_CHECKLIST = [
    'Trailing 12-month P&L and balance sheet',
    'ARR/MRR cohort analysis and churn report',
    'Customer contracts & top-20 customer list',
    'Product roadmap and release cadence history',
    'Security, compliance, and privacy documentation',
    'IP assignments, cap table, and option plan',
    'Infrastructure costs and vendor agreements',
    'Support tickets, NPS, and CSAT summaries'
];

/**
 * Generate a basic FREE PDF report (1-2 pages)
 * UPDATED: Matches Pro Styling
 */
export function generateFreePDF(data: ValuationResult, inputs: ValuationInputs) {
    const doc = new jsPDF();
    const companyName = inputs.companyName || 'Your SaaS';

    // --- PAGE 1: COVER ---
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');

    doc.setDrawColor(14, 165, 233);
    doc.setLineWidth(2);
    doc.line(MARGIN, 100, MARGIN + 50, 100);

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(40);
    doc.text('Valuation', MARGIN, 140);
    doc.text('Report', MARGIN, 155);

    doc.setFontSize(22);
    doc.setTextColor(148, 163, 184);
    doc.text(companyName.toUpperCase(), MARGIN, 175);

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    let infoY = 185;
    if (inputs.email) {
        doc.text(`Email: ${inputs.email}`, MARGIN, infoY);
        infoY += 6;
    }
    if (inputs.website) {
        doc.text(`Website: ${inputs.website}`, MARGIN, infoY);
        infoY += 6;
    }

    doc.setFontSize(10);
    doc.text('FREE EDITION - BASIC SUMMARY', MARGIN, 240);
    doc.text(`DATE PREPARED: ${new Date().toLocaleDateString()}`, MARGIN, 247);

    // --- PAGE 2: VALUATION SUMMARY ---
    doc.addPage();
    drawHeader(doc, 'Valuation Summary', false);
    let y = 50;
    y = drawSectionTitle(doc, 'Estimated Market Value', y);
    y = drawSummaryBox(doc, y, companyName, data.avgValuation, data.rangeLow, data.rangeHigh, data.confidence);

    const insights = buildInsights(data, inputs);

    y = drawSectionTitle(doc, 'Valuation Methods', y);
    const methodRows = data.valuations.map(v => [v.method, formatCurrency(v.value)]);
    y = drawDataTable(doc, ['Method', 'Estimated Value'], methodRows, y);

    // --- PAGE 3: KEY METRICS ---
    doc.addPage();
    drawHeader(doc, 'Key Metrics', false);
    y = 50;
    y = drawSectionTitle(doc, 'Operating Metrics & Benchmarks', y);

    const metricsRows = [
        ['Growth (YoY)', formatPercent(inputs.growthYoy), getBenchmarkStatus(inputs.growthYoy, 20)],
        ['Gross Margin', formatPercent(inputs.grossMargin), getBenchmarkStatus(inputs.grossMargin, 70)],
        ['Net Profit Margin', formatPercent(insights.netProfitMargin), getBenchmarkStatus(insights.netProfitMargin, 10)],
        ['Customer Churn', formatPercent(inputs.customerChurn), getBenchmarkStatus(inputs.customerChurn, undefined, 5)],
        ['Net Retention', formatPercent(inputs.retentionRate), getBenchmarkStatus(inputs.retentionRate, 100)],
        ['LTV / CAC', formatRatio(insights.ltvCac), getBenchmarkStatus(insights.ltvCac, 3)],
        ['CAC Payback (months)', formatNumber(insights.payback), getBenchmarkStatus(insights.payback, undefined, 12)],
        ['Revenue Multiple', formatRatio(insights.revenueMultiple), getBenchmarkStatus(insights.revenueMultiple, 4)],
    ];
    y = drawDataTable(doc, ['Metric', 'Value', 'Benchmark'], metricsRows, y);

    y = drawSectionTitle(doc, 'Top Opportunities', y + 10);
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    doc.setFont('helvetica', 'normal');
    const opportunitiesText = insights.opportunities.map((item, index) => `${index + 1}. ${item}`).join('\n');
    const splitOpportunities = doc.splitTextToSize(opportunitiesText, CONTENT_WIDTH);
    doc.text(splitOpportunities, MARGIN, y);
    y += (splitOpportunities.length * 5) + 10;

    y = drawSectionTitle(doc, 'Risk Flags', y);
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    const riskText = insights.risks.map((item, index) => `${index + 1}. ${item}`).join('\n');
    const splitRisks = doc.splitTextToSize(riskText, CONTENT_WIDTH);
    doc.text(splitRisks, MARGIN, y);
    y += (splitRisks.length * 5) + 10;

    // --- PAGE 4: AI ANALYSIS & DATA ROOM ---
    doc.addPage();
    drawHeader(doc, 'Expert Analysis', false);
    y = 50;
    y = drawSectionTitle(doc, '🤖 AI Expert Analysis', y);

    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    doc.setFont('helvetica', 'italic');
    const analysis = generateAIAnalysis(inputs, companyName);
    const splitAnalysis = doc.splitTextToSize(analysis.replace(/\*\*/g, ''), CONTENT_WIDTH);
    doc.text(splitAnalysis, MARGIN, y);
    y += (splitAnalysis.length * 5) + 15;

    y = drawSectionTitle(doc, 'Data Room Checklist', y);
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    doc.setFont('helvetica', 'normal');
    const checklistText = DATA_ROOM_CHECKLIST.map(item => `• ${item}`).join('\n');
    const splitChecklist = doc.splitTextToSize(checklistText, CONTENT_WIDTH);
    doc.text(splitChecklist, MARGIN, y);
    y += (splitChecklist.length * 5) + 15;

    if (insights.qualityFlags.length) {
        y = drawSectionTitle(doc, 'Data Quality Notes', y);
        const qualityText = insights.qualityFlags.map(item => `• ${item}`).join('\n');
        const splitQuality = doc.splitTextToSize(qualityText, CONTENT_WIDTH);
        doc.text(splitQuality, MARGIN, y);
        y += (splitQuality.length * 5) + 10;
    }

    // Upgrade CTA Section (Pro Style)
    doc.setFillColor(248, 250, 252); // slate-50
    doc.setDrawColor(226, 232, 240); // slate-200
    doc.rect(MARGIN, y, CONTENT_WIDTH, 50, 'FD');

    doc.setTextColor(15, 23, 42);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Want 10+ Pages of Detailed Insights?', PAGE_WIDTH / 2, y + 15, { align: 'center' });

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const ctaText = 'Upgrade to the Pro Report for deep financial dives, benchmarking against 10,000+ deals, unit economics, exit scenarios, and buyer profiles.';
    const splitCta = doc.splitTextToSize(ctaText, CONTENT_WIDTH - 20);
    doc.text(splitCta, PAGE_WIDTH / 2, y + 25, { align: 'center' });

    doc.setTextColor(14, 165, 233);
    doc.setFont('helvetica', 'bold');
    doc.text('Get Pro for $19 at saasvaluation.app/pro', PAGE_WIDTH / 2, y + 42, { align: 'center' });

    // Footers for all pages
    const pageCount = (doc.internal as any).getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        if (i > 1) drawFooter(doc, i, pageCount);
    }

    doc.save(`${companyName.replace(/\s+/g, '-').toLowerCase()}-valuation-free.pdf`);
}

/**
 * Generate a comprehensive PRO PDF report (10 pages)
 */
export function generateProPDF(data: ValuationResult, inputs: any, companyName: string = 'Your SaaS') {
    const doc = new jsPDF();

    // Helper functions within Pro use the shared ones now
    const drawSectionTitleLocal = (title: string, y: number) => drawSectionTitle(doc, title, y);
    const drawDataTableLocal = (headers: string[], rows: any[][], y: number) => drawDataTable(doc, headers, rows, y);

    const drawBarChart = (chartData: { name: string, value: number }[], y: number, height: number = 60) => {
        const barWidth = (CONTENT_WIDTH - 20) / chartData.length;
        const maxValue = Math.max(...chartData.map(d => d.value));
        const chartY = y + height;

        chartData.forEach((d, i) => {
            const barHeight = (d.value / maxValue) * (height - 15);
            const x = MARGIN + 10 + (i * barWidth);

            // Draw Bar
            doc.setFillColor(14, 165, 233); // brand-500
            doc.rect(x + (barWidth * 0.2), chartY - barHeight, barWidth * 0.6, barHeight, 'F');

            // Labels
            doc.setFontSize(7);
            doc.setTextColor(51, 65, 85);
            doc.text(d.name, x + (barWidth / 2), chartY + 5, { align: 'center', maxWidth: barWidth * 0.8 });
            doc.setFont('helvetica', 'bold');
            doc.text(formatCurrency(d.value), x + (barWidth / 2), chartY - barHeight - 3, { align: 'center' });
            doc.setFont('helvetica', 'normal');
        });

        return chartY + 20;
    };

    const drawBenchmarkChart = (benchmarks: { label: string, score: number, target: number }[], y: number) => {
        let currentY = y;
        const labelWidth = 50;
        const barAreaWidth = CONTENT_WIDTH - labelWidth - 20;

        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text('SCORE (%)', MARGIN + labelWidth + (barAreaWidth / 2), currentY, { align: 'center' });
        currentY += 8;

        benchmarks.forEach(b => {
            doc.setFontSize(9);
            doc.setTextColor(15, 23, 42);
            doc.text(b.label, MARGIN, currentY + 4);

            // Background bar
            doc.setFillColor(241, 245, 249);
            doc.rect(MARGIN + labelWidth, currentY, barAreaWidth, 5, 'F');

            // Score bar
            const scoreWidth = (b.score / 100) * barAreaWidth;
            doc.setFillColor(14, 165, 233);
            doc.rect(MARGIN + labelWidth, currentY, scoreWidth, 5, 'F');

            // Target marker
            const targetX = MARGIN + labelWidth + ((b.target / 100) * barAreaWidth);
            doc.setDrawColor(245, 158, 11); // amber-500
            doc.setLineWidth(1);
            doc.line(targetX, currentY - 2, targetX, currentY + 7);

            currentY += 15;
        });

        return currentY;
    };

    // --- PAGE 1: TITLE PAGE ---
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');

    doc.setDrawColor(14, 165, 233);
    doc.setLineWidth(2);
    doc.line(MARGIN, 100, MARGIN + 50, 100);

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(40);
    doc.text('Valuation', MARGIN, 140);
    doc.text('Analysis', MARGIN, 155);

    doc.setFontSize(22);
    doc.setTextColor(148, 163, 184);
    doc.text(companyName.toUpperCase(), MARGIN, 175);

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    let infoY = 185;
    if (inputs.email) {
        doc.text(`Email: ${inputs.email}`, MARGIN, infoY);
        infoY += 6;
    }
    if (inputs.website) {
        doc.text(`Website: ${inputs.website}`, MARGIN, infoY);
        infoY += 6;
    }

    doc.setFillColor(14, 165, 233);
    doc.rect(MARGIN, infoY + 2, 60, 2, 'F');

    doc.setFontSize(10);
    doc.text('INVESTOR-GRADE PROFESSIONAL REPORT', MARGIN, 240);
    doc.text(`DATE PREPARED: ${new Date().toLocaleDateString()}`, MARGIN, 247);
    doc.text('PROVIDED BY THE SAAS VALUATION WIZARD', MARGIN, 254);

    // --- PAGE 2: EXECUTIVE SUMMARY ---
    doc.addPage();
    drawHeader(doc, 'Executive Summary', true);
    let y = 50;
    y = drawSectionTitle(doc, 'Valuation Overview', y);
    y = drawSummaryBox(doc, y, companyName, data.avgValuation, data.rangeLow, data.rangeHigh, data.confidence);

    y = drawSectionTitle(doc, 'The Bottom Line', y);
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    const bottomLineArr = doc.splitTextToSize(
        `Based on an ARR of ${formatCurrency(inputs.arr)} and a growth profile of ${inputs.growthYoy}%, ${companyName} displays a consistent valuation trajectory. The average ARR multiple of ${(data.avgValuation / (inputs.arr || 1)).toFixed(1)}x is indicative of a healthy SaaS profile in the current market. Strategic improvements in churn and net retention could yield an additional 15-20% in value uplift over the next 12 months.`,
        CONTENT_WIDTH
    );
    doc.text(bottomLineArr, MARGIN, y);

    // --- PAGE 3: FINANCIAL DEEP DIVE ---
    doc.addPage();
    drawHeader(doc, 'Financial Snapshot', true);
    y = 40;
    y = drawSectionTitle(doc, 'Base Financials', y);

    const financialRows = [
        ['Metric', 'Current Value', 'Benchmark (SaaS)'],
        ['Annual Recurring Revenue (ARR)', formatCurrency(inputs.arr), '> $1M (Growth Stage)'],
        ['Monthly Recurring Revenue (MRR)', formatCurrency(inputs.mrr), 'N/A'],
        ['Net Profit (EBITDA)', formatCurrency(inputs.netProfit), '10-20% Margin'],
        ['Gross Margin', `${inputs.grossMargin || 80}%`, '75-85% (Target)'],
        ['Annual Contract Value (ACV)', formatCurrency(inputs.contractValue || 0), 'Segment Dependent'],
    ];
    y = drawDataTable(doc, financialRows[0], financialRows.slice(1), y);

    y += 15;
    y = drawSectionTitle(doc, 'Valuation Composition', y);
    const chartData = data.valuations.map(v => ({ name: v.method, value: v.value }));
    y = drawBarChart(chartData, y, 50);

    y += 10;
    y = drawSectionTitle(doc, 'Profitability Analysis', y);
    const marginPercent = ((inputs.netProfit / (inputs.arr || 1)) * 100).toFixed(1);
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    doc.text(`Your current EBITDA margin is ${marginPercent}%.`, MARGIN, y);
    y += 10;

    doc.setFillColor(241, 245, 249);
    doc.rect(MARGIN, y, CONTENT_WIDTH, 5, 'F');
    const marginWidth = Math.min(Math.max(Number(marginPercent), 0), 100) / 100 * CONTENT_WIDTH;
    doc.setFillColor(14, 165, 233);
    doc.rect(MARGIN, y, marginWidth, 5, 'F');

    // --- PAGE 4: VALUATION METHODOLOGIES (1 & 2) ---
    doc.addPage();
    drawHeader(doc, 'Valuation Methodology Part I', true);
    y = 40;
    y = drawSectionTitle(doc, '1. Revenue Multiplier Method', y);
    doc.setFontSize(10);
    doc.setTextColor(71, 85, 105);
    doc.text('This method applies an industry-specific multiple to your ARR, adjusted for growth and churn.', MARGIN, y);
    y += 10;

    const revVal = data.valuations.find(v => v.method.includes('Revenue'))?.value || 0;
    doc.setFillColor(248, 250, 252);
    doc.rect(MARGIN, y, CONTENT_WIDTH, 15, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(14, 165, 233);
    doc.text(`Estimated Value: ${formatCurrency(revVal)}`, MARGIN + 5, y + 10);
    doc.setFont('helvetica', 'normal');
    y += 25;

    y = drawSectionTitle(doc, '2. Income-Based / SDE Method', y);
    doc.setFontSize(10);
    doc.setTextColor(71, 85, 105);
    doc.text('Primarily for bootstrapped companies, this looks at the Sellers Discretionary Earnings (SDE).', MARGIN, y);
    y += 10;

    const incomeVal = data.valuations.find(v => v.method.includes('Income'))?.value || 0;
    doc.setFillColor(248, 250, 252);
    doc.rect(MARGIN, y, CONTENT_WIDTH, 15, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(14, 165, 233);
    doc.text(`Estimated Value: ${formatCurrency(incomeVal)}`, MARGIN + 5, y + 10);
    doc.setFont('helvetica', 'normal');

    // --- PAGE 5: VALUATION METHODOLOGIES (3 & 4) ---
    doc.addPage();
    drawHeader(doc, 'Valuation Methodology Part II', true);
    y = 40;
    y = drawSectionTitle(doc, '3. Rule of 40 / Efficiency Method', y);
    doc.setFontSize(10);
    doc.text('Adjusts valuation based on the "Rule of 40" - the sum of growth and profit margin.', MARGIN, y);
    y += 10;

    const earnVal = data.valuations.find(v => v.method.includes('Earnings'))?.value || 0;
    doc.setFillColor(248, 250, 252);
    doc.rect(MARGIN, y, CONTENT_WIDTH, 15, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(14, 165, 233);
    doc.text(`Estimated Value: ${formatCurrency(earnVal)}`, MARGIN + 5, y + 10);
    doc.setFont('helvetica', 'normal');
    y += 25;

    y = drawSectionTitle(doc, '4. Discounted Cash Flow (DCF)', y);
    doc.setFontSize(10);
    doc.text(`Projected future cash flows discounted at an annual rate of ${(inputs.discountRate * 100).toFixed(1)}%.`, MARGIN, y);
    y += 10;

    const dcfVal = data.valuations.find(v => v.method.includes('DCF'))?.value || 0;
    doc.setFillColor(248, 250, 252);
    doc.rect(MARGIN, y, CONTENT_WIDTH, 15, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(14, 165, 233);
    doc.text(`Estimated Value: ${formatCurrency(dcfVal)}`, MARGIN + 5, y + 10);
    doc.setFont('helvetica', 'normal');

    // --- PAGE 6: GROWTH & CHURN DYNAMICS ---
    doc.addPage();
    drawHeader(doc, 'Growth & Retention Analysis', true);
    y = 40;
    y = drawSectionTitle(doc, 'Retention Benchmarks', y);

    const churnRows = [
        ['Metric', 'Your Score', 'Benchmark (Target)'],
        ['Gross Churn (Monthly)', `${inputs.customerChurn}%`, '< 1.5%'],
        ['Net Dollar Retention (NDR)', `${inputs.retentionRate}%`, '> 100%'],
        ['Revenue Churn', `${inputs.revenueChurn || inputs.customerChurn}%`, '< 1.0%'],
    ];
    y = drawDataTable(doc, churnRows[0], churnRows.slice(1), y);

    y += 20;
    y = drawSectionTitle(doc, 'The Churn Impact', y);
    doc.setFontSize(10);
    const churnFactor = inputs.customerChurn > 3 ? 'high' : 'healthy';
    doc.text(`A churn rate of ${inputs.customerChurn}% is considered ${churnFactor}.`, MARGIN, y);
    y += 10;
    doc.text('Compounding impact of churn over 3 years:', MARGIN, y);
    y += 10;

    const threeYearRetention = Math.pow(1 - (inputs.customerChurn / 100), 36).toFixed(1);
    doc.setFillColor(241, 245, 249);
    doc.rect(MARGIN, y, CONTENT_WIDTH, 20, 'F');
    doc.setTextColor(220, 38, 38);
    doc.setFont('helvetica', 'bold');
    doc.text(`Only ${(Number(threeYearRetention) * 100).toFixed(1)}% of your current revenue would remain in 36 months without expansion.`, MARGIN + 5, y + 12);

    // --- PAGE 7: UNIT ECONOMICS & EFFICIENCY ---
    doc.addPage();
    drawHeader(doc, 'Unit Economics & Efficiency', true);
    y = 40;
    y = drawSectionTitle(doc, 'Efficiency Metrics', y);

    const ltvCac = inputs.cac > 0 ? (inputs.ltv / inputs.cac).toFixed(1) : 'N/A';
    const netMarginRate = (inputs.netProfit / (inputs.arr || 1));
    const ruleOf40 = (inputs.growthYoy + (netMarginRate * 100)).toFixed(1);
    const paybackPeriod = inputs.cac > 0 && inputs.mrr > 0 && inputs.activeCustomers > 0
        ? (inputs.cac / (inputs.mrr / inputs.activeCustomers)).toFixed(1)
        : 'Calc Error';

    const efficiencyRows = [
        ['Metric', 'Your Value', 'Excellence Threshold'],
        ['LTV : CAC Ratio', `${ltvCac}:1`, '3.0:1 or better'],
        ['Payback Period', `${paybackPeriod} mo`, '< 12 months'],
        ['Rule of 40 Score', `${ruleOf40}%`, '> 40%'],
    ];
    y = drawDataTable(doc, efficiencyRows[0], efficiencyRows.slice(1), y);

    y += 15;
    y = drawSectionTitle(doc, 'Peer Benchmarking', y);
    const benchmarks = [
        { label: 'Growth Rating', score: 80, target: 45 },
        { label: 'Retention Health', score: data.confidence, target: 85 },
        { label: 'Profit Efficiency', score: 60, target: 20 },
        { label: 'Market Position', score: 70, target: 50 },
        { label: 'Tech Stack Maturity', score: 90, target: 75 },
    ];
    y = drawBenchmarkChart(benchmarks, y);

    y += 10;
    y = drawSectionTitle(doc, 'Metric Deep Dive', y);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text('The Rule of 40 Analysis', MARGIN, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    y += 7;
    const rule40Desc = doc.splitTextToSize(
        `The Rule of 40 is a high-level health metric for SaaS companies. It states that your growth rate plus your profit margin should be 40 or higher. Your score of ${ruleOf40}% indicates that the business is currently ${Number(ruleOf40) >= 40 ? 'performing at an elite level' : 'balancing growth and profit; focus on optimizing one to hit the 40% benchmark'}.`,
        CONTENT_WIDTH
    );
    doc.text(rule40Desc, MARGIN, y);

    // --- PAGE 8: MOAT & RISK ASSESSMENT ---
    doc.addPage();
    drawHeader(doc, 'Moat & Risk Matrix', true);
    y = 40;
    y = drawSectionTitle(doc, 'Strategic Scoring', y);

    const calculateScore = (val: string) => {
        if (val === 'none' || val === 'no') return 2;
        if (val === 'partial' || val === 'licensed') return 6;
        return 10;
    };

    const riskRows = [
        ['Factor', 'Status', 'Risk Score (1-10)'],
        ['IP Ownership', inputs.ipOwnership || 'Standard', calculateScore(inputs.ipOwnership || '')],
        ['Legal Standing', inputs.legalIssues || 'Clean', inputs.legalIssues === 'none' ? 10 : 4],
        ['Founder Dependency', `${inputs.keyStaff || 0} Key Staff`, (inputs.keyStaff || 0) > 2 ? 8 : 5],
        ['Tech Scalability', inputs.scalableInfrastructure || 'N/A', calculateScore(inputs.scalableInfrastructure || '')],
        ['Data Compliance', inputs.dataPrivacy || 'N/A', calculateScore(inputs.dataPrivacy || '')],
    ];
    y = drawDataTable(doc, riskRows[0], riskRows.slice(1), y);

    y += 20;
    y = drawSectionTitle(doc, 'Moat Analysis', y);
    doc.setFontSize(10);
    const ipBonus = inputs.ipOwnership === 'fully-owned' ? 'Your proprietary IP provides a strong defensive moat.' : 'Strengthening IP ownership could significantly reduce risk discounts.';
    doc.text(ipBonus, MARGIN, y);
    y += 7;
    doc.text(`With ${inputs.keyStaff || 1} key personnel, transition risk is ${(inputs.keyStaff || 1) > 2 ? 'moderate' : 'low'}.`, MARGIN, y);

    // --- PAGE 9: EXIT SCENARIOS & BUYER PROFILES ---
    doc.addPage();
    drawHeader(doc, 'Exit & Buyer Analysis', true);
    y = 40;
    y = drawSectionTitle(doc, 'Modeled Exit Scenarios', y);

    const exitData = [
        ['Scenario', 'Multiple', 'Enterprise Value'],
        ['Conservative (3x)', '3.0x', formatCurrency(inputs.arr * 3)],
        ['Current Model (Base)', `${(data.avgValuation / inputs.arr).toFixed(1)}x`, formatCurrency(data.avgValuation)],
        ['Strategic (8x Target)', '8.0x', formatCurrency(inputs.arr * 8)],
    ];
    y = drawDataTable(doc, exitData[0], exitData.slice(1), y);

    y += 20;
    y = drawSectionTitle(doc, 'Strategic Buyer Analysis', y);
    const buyers = [
        { type: 'Strategic Acquirer', premium: '20-50%', profile: 'Looking for product/tech synergy' },
        { type: 'Private Equity (PE)', premium: '5-15%', profile: 'Looking for efficiency and EBITDA' },
        { type: 'Direct Competitor', premium: '15-30%', profile: 'Looking for market share expansion' },
    ];

    buyers.forEach(b => {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(14, 165, 233);
        doc.text(b.type, MARGIN, y);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(71, 85, 105);
        doc.text(`Premium: ${b.premium} • ${b.profile}`, MARGIN + 50, y);
        y += 10;
    });

    // --- PAGE 10: ACTION ROADMAP ---
    doc.addPage();
    drawHeader(doc, 'Strategic Action Roadmap', true);
    y = 40;
    y = drawSectionTitle(doc, 'Priority 1: Immediate Value Uplift', y);

    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    const recommendations = [];
    if (inputs.customerChurn > 3) recommendations.push('Aggressively target churn reduction. A 1% drop in churn yields ~15% valuation growth over 24 months.');
    if (inputs.retentionRate < 100) recommendations.push('Focus on net expansion/upsells. NDR over 100% is the primary differentiator for top-tier multiples.');
    if (inputs.growthYoy < 30) recommendations.push('Explore new acquisition channels. Valuation multiples step up significantly once growth crosses the 30% hurdle.');
    if (recommendations.length === 0) recommendations.push('Maintain current performance. The business is currently in the top 10% of efficiency metrics for its category.');

    recommendations.forEach(rec => {
        doc.circle(MARGIN + 2, y - 1, 1, 'F');
        doc.text(rec, MARGIN + 7, y);
        y += 10;
    });

    y += 15;
    y = drawSectionTitle(doc, 'Glossary of Terms', y);
    y -= 5;
    const glossary = [
        ['ARR', 'Annual Recurring Revenue - total predictable revenue in a year.'],
        ['EBITDA', 'Earnings Before Interest, Taxes, Depreciation, and Amortization.'],
        ['NDR', 'Net Dollar Retention - revenue retained from the same customer cohort. High NDR over 100% means the product grows itself.'],
        ['CAC Payback', 'The time taken to earn back the cost of acquiring one customer. Target is under 12 months for most SaaS models.'],
    ];
    glossary.forEach(item => {
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(15, 23, 42);
        doc.text(item[0], MARGIN, y);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(71, 85, 105);
        const splitDesc = doc.splitTextToSize(item[1], CONTENT_WIDTH - 30);
        doc.text(splitDesc, MARGIN + 30, y);
        y += (splitDesc.length * 5) + 2;
    });

    // Footers for all pages
    const pageCount = (doc.internal as any).getNumberOfPages();
    for (let i = 2; i <= pageCount; i++) {
        doc.setPage(i);
        drawFooter(doc, i, pageCount);
    }

    doc.save(`${companyName.replace(/\s+/g, '-').toLowerCase()}-investor-valuation.pdf`);
}
